name: WFB-ng package builder for ubuntu

on:
  push:
    branches: [ master, release-24.08, release-25.01 ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master, stable ]

jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        version: [ "20.04", "22.04", "24.04" ]
        arch: [ "armhf.arm32v7.max", "arm64.arm64v8.cortex-a53", "amd64.amd64.max"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: build package
        run: |
          curl -s -L https://github.com/svpcom/wfb-ng/releases/download/wifibroadcast-17.10/qemu-7.2.15-fixed.tar.gz | sudo tar xzv -C /
          make deb_docker QEMU_CPU=$(echo ${{ matrix.arch }} | cut -f3 -d.) DOCKER_ARCH=$(echo ${{ matrix.arch }} | cut -f1 -d.) DOCKER_SRC_IMAGE=$(echo ${{ matrix.arch }} | cut -f2 -d.)/ubuntu:${{ matrix.version }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        if: github.event_name != 'pull_request'
        with:
          name: wfb-ng-${{ github.ref_name }}-ubuntu${{ matrix.version }}-${{ matrix.arch }}
          path: |
            deb_dist/*.deb
